#!/bin/sh

mkdir -p /var/mobile/Library/Caches/xyz.willy.aupm/
chown mobile:mobile /var/mobile/Library/Caches/xyz.willy.aupm/

chown root:wheel /Applications/AUPM.app/supersling
chmod 6755 /Applications/AUPM.app/supersling
chmod 0777 /var/lib/aupm/database
